name: DavoDays
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181619'
    - '#544c59'
    - '#758eab'
    - '#fdb82c'
    - '#b97d52'
  brandStrength: 0
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 1
purpose: []
