name: DavoDays
favicon: null
layout_spectrum: 0.13746
typography_spectrum: 0.11849
title: DavoDays
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9ccde1'
    - '#4e4757'
    - '#518aad'
    - '#92a7bb'
    - '#91aa32'
  brandStrength: 0
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
